version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: energy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: nest_user
      DB_PASSWORD: nest_password
      DB_NAME: energy
      DB_HOST: 44.226.145.213
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
